### ISSUE TITLE
TypeError: expected string or buffer

### ISSUE THREAD

**Issue by cynnog** [amarder/diamonds#2]
Hi,

I'm trying to run your script, but got the following errors:

python download.py --shape RD > my-diamonds.csv

Traceback (most recent call last):
  File "download.py", line 122, in <module>
    main()
  File "download.py", line 116, in main
    l = diamonds(params)
  File "download.py", line 31, in diamonds
    d['results'][i]['price'] = _price_to_int(d['results'][i]['price'])
  File "download.py", line 10, in _price_to_int
    return int(re.sub('[$,]', '', s))
  File "/usr/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer

and executed with python3:

python3 download.py --shape RD > my-diamond.csv
  File "download.py", line 118
    print df.to_csv('bako.csv', index=False)
           ^
SyntaxError: invalid syntax
 

Could you please advise how to proceed? (sorry I'm new to python)

Best regards

**Comment by amarder** [comment]
No worries, I haven't run this code in a while. In fact, I think we should abandon this code.

Here's a quick description of a newer project that actually works (using Python 2.7): http://disq.us/p/1f3e433

**Comment by cynnog** [comment]
Ok, thank you very much!
